"""
Flamezo niche taxonomy — canonical flat mapping shared by AI endpoints.
id → breadcrumb ("Industry > Category > Specialisation")
"""

TAXONOMY: dict[str, str] = {
    # Dining
    "dining": "Dining",
    "dining-fine": "Dining > Fine Dining",
    "dining-fine-continental": "Dining > Fine Dining > Continental",
    "dining-fine-asian": "Dining > Fine Dining > Asian Fusion",
    "dining-fine-indian": "Dining > Fine Dining > Indian",
    "dining-fine-mediterranean": "Dining > Fine Dining > Mediterranean",
    "dining-casual": "Dining > Casual Dining",
    "dining-casual-family": "Dining > Casual Dining > Family Style",
    "dining-casual-bistro": "Dining > Casual Dining > Bistro",
    "dining-casual-american": "Dining > Casual Dining > American",
    "dining-cafe": "Dining > Café",
    "dining-cafe-specialty": "Dining > Café > Specialty Coffee",
    "dining-cafe-dessert": "Dining > Café > Dessert Café",
    "dining-cafe-brunch": "Dining > Café > Brunch Spot",
    "dining-fastfood": "Dining > Fast Food",
    "dining-fastfood-burger": "Dining > Fast Food > Burgers",
    "dining-fastfood-pizza": "Dining > Fast Food > Pizza",
    "dining-fastfood-wraps": "Dining > Fast Food > Wraps & Rolls",
    "dining-fastfood-chinese": "Dining > Fast Food > Chinese",
    "dining-bar": "Dining > Bar & Lounge",
    "dining-bar-cocktail": "Dining > Bar & Lounge > Cocktail Bar",
    "dining-bar-sports": "Dining > Bar & Lounge > Sports Bar",
    "dining-bar-rooftop": "Dining > Bar & Lounge > Rooftop Bar",
    "dining-bakery": "Dining > Bakery & Patisserie",
    "dining-bakery-artisan": "Dining > Bakery & Patisserie > Artisan Bread",
    "dining-bakery-cakes": "Dining > Bakery & Patisserie > Custom Cakes",
    "dining-bakery-pastry": "Dining > Bakery & Patisserie > Pastry",
    "dining-cloud": "Dining > Cloud Kitchen",
    "dining-cloud-tiffin": "Dining > Cloud Kitchen > Tiffin Service",
    "dining-cloud-meals": "Dining > Cloud Kitchen > Meal Preps",
    "dining-streetfood": "Dining > Street Food",
    "dining-streetfood-chaat": "Dining > Street Food > Chaat",
    "dining-streetfood-dosa": "Dining > Street Food > Dosa & South Indian",
    "dining-streetfood-grill": "Dining > Street Food > Grills & Kebabs",
    # Fashion
    "fashion": "Fashion",
    "fashion-tailoring": "Fashion > Tailoring",
    "fashion-tailoring-mens": "Fashion > Tailoring > Men's Tailoring",
    "fashion-tailoring-womens": "Fashion > Tailoring > Women's Tailoring",
    "fashion-tailoring-bridal": "Fashion > Tailoring > Bridal Wear",
    "fashion-tailoring-alterations": "Fashion > Tailoring > Alterations",
    "fashion-retail": "Fashion > Retail",
    "fashion-retail-ethnic": "Fashion > Retail > Ethnic Wear",
    "fashion-retail-western": "Fashion > Retail > Western Wear",
    "fashion-retail-kids": "Fashion > Retail > Kids' Fashion",
    "fashion-retail-streetwear": "Fashion > Retail > Streetwear",
    "fashion-retail-luxury": "Fashion > Retail > Luxury",
    "fashion-rental": "Fashion > Rental",
    "fashion-rental-occasion": "Fashion > Rental > Occasion Wear",
    "fashion-rental-costume": "Fashion > Rental > Costumes",
    "fashion-rental-designer": "Fashion > Rental > Designer Rental",
    "fashion-accessories": "Fashion > Accessories",
    "fashion-accessories-bags": "Fashion > Accessories > Bags & Handbags",
    "fashion-accessories-jewellery": "Fashion > Accessories > Jewellery",
    "fashion-accessories-footwear": "Fashion > Accessories > Footwear",
    "fashion-accessories-watches": "Fashion > Accessories > Watches",
    "fashion-designer": "Fashion > Designer Studio",
    "fashion-designer-couture": "Fashion > Designer Studio > Couture",
    "fashion-designer-ready": "Fashion > Designer Studio > Ready-to-Wear",
    # Wellness
    "wellness": "Wellness",
    "wellness-spa": "Wellness > Spa & Massage",
    "wellness-spa-thai": "Wellness > Spa & Massage > Thai Massage",
    "wellness-spa-deep": "Wellness > Spa & Massage > Deep Tissue",
    "wellness-spa-aromatherapy": "Wellness > Spa & Massage > Aromatherapy",
    "wellness-spa-couples": "Wellness > Spa & Massage > Couples' Spa",
    "wellness-yoga": "Wellness > Yoga",
    "wellness-yoga-hatha": "Wellness > Yoga > Hatha",
    "wellness-yoga-vinyasa": "Wellness > Yoga > Vinyasa",
    "wellness-yoga-prenatal": "Wellness > Yoga > Prenatal",
    "wellness-yoga-kids": "Wellness > Yoga > Kids Yoga",
    "wellness-meditation": "Wellness > Meditation",
    "wellness-meditation-guided": "Wellness > Meditation > Guided Sessions",
    "wellness-meditation-sound": "Wellness > Meditation > Sound Healing",
    "wellness-meditation-mindfulness": "Wellness > Meditation > Mindfulness",
    "wellness-ayurveda": "Wellness > Ayurveda",
    "wellness-ayurveda-panchakarma": "Wellness > Ayurveda > Panchakarma",
    "wellness-ayurveda-herbal": "Wellness > Ayurveda > Herbal Treatments",
    "wellness-nutrition": "Wellness > Nutrition & Diet",
    "wellness-nutrition-consulting": "Wellness > Nutrition & Diet > Diet Consulting",
    "wellness-nutrition-weight": "Wellness > Nutrition & Diet > Weight Management",
    "wellness-float": "Wellness > Float Therapy",
    # Beauty
    "beauty": "Beauty",
    "beauty-hair": "Beauty > Hair",
    "beauty-hair-salon": "Beauty > Hair > Salon",
    "beauty-hair-color": "Beauty > Hair > Colouring & Highlights",
    "beauty-hair-extensions": "Beauty > Hair > Extensions",
    "beauty-hair-treatment": "Beauty > Hair > Treatments & Spa",
    "beauty-hair-mens": "Beauty > Hair > Men's Grooming",
    "beauty-hair-barber": "Beauty > Hair > Barbershop",
    "beauty-skin": "Beauty > Skin Care",
    "beauty-skin-facial": "Beauty > Skin Care > Facials",
    "beauty-skin-acne": "Beauty > Skin Care > Acne Treatment",
    "beauty-skin-antiaging": "Beauty > Skin Care > Anti-Ageing",
    "beauty-skin-derma": "Beauty > Skin Care > Dermatology",
    "beauty-nails": "Beauty > Nails",
    "beauty-nails-gel": "Beauty > Nails > Gel & Acrylics",
    "beauty-nails-nail-art": "Beauty > Nails > Nail Art",
    "beauty-nails-pedicure": "Beauty > Nails > Pedicure",
    "beauty-makeup": "Beauty > Makeup",
    "beauty-makeup-bridal": "Beauty > Makeup > Bridal Makeup",
    "beauty-makeup-studio": "Beauty > Makeup > Studio Makeup",
    "beauty-makeup-lessons": "Beauty > Makeup > Makeup Lessons",
    "beauty-waxing": "Beauty > Waxing & Threading",
    "beauty-tattoo": "Beauty > Tattoo & Piercing",
    "beauty-tattoo-fine": "Beauty > Tattoo & Piercing > Fine Line",
    "beauty-tattoo-traditional": "Beauty > Tattoo & Piercing > Traditional",
    # Sports
    "sports": "Sports",
    "sports-courts": "Sports > Court Sports",
    "sports-courts-badminton": "Sports > Court Sports > Badminton",
    "sports-courts-tennis": "Sports > Court Sports > Tennis",
    "sports-courts-squash": "Sports > Court Sports > Squash",
    "sports-courts-basketball": "Sports > Court Sports > Basketball",
    "sports-courts-volleyball": "Sports > Court Sports > Volleyball",
    "sports-fitness": "Sports > Fitness",
    "sports-fitness-gym": "Sports > Fitness > Gym",
    "sports-fitness-crossfit": "Sports > Fitness > CrossFit",
    "sports-fitness-pilates": "Sports > Fitness > Pilates",
    "sports-fitness-zumba": "Sports > Fitness > Zumba & Dance",
    "sports-fitness-functional": "Sports > Fitness > Functional Training",
    "sports-martial": "Sports > Martial Arts",
    "sports-martial-mma": "Sports > Martial Arts > MMA",
    "sports-martial-boxing": "Sports > Martial Arts > Boxing",
    "sports-martial-karate": "Sports > Martial Arts > Karate",
    "sports-martial-judo": "Sports > Martial Arts > Judo",
    "sports-martial-taekwondo": "Sports > Martial Arts > Taekwondo",
    "sports-swimming": "Sports > Swimming",
    "sports-swimming-coaching": "Sports > Swimming > Coaching",
    "sports-swimming-lap": "Sports > Swimming > Lap Pool",
    "sports-cricket": "Sports > Cricket",
    "sports-cricket-academy": "Sports > Cricket > Academy",
    "sports-cricket-nets": "Sports > Cricket > Practice Nets",
    "sports-football": "Sports > Football / Futsal",
    "sports-cycling": "Sports > Cycling",
    "sports-shooting": "Sports > Shooting & Archery",
    # Retail
    "retail": "Retail",
    "retail-electronics": "Retail > Electronics",
    "retail-electronics-phones": "Retail > Electronics > Phones & Accessories",
    "retail-electronics-gadgets": "Retail > Electronics > Gadgets",
    "retail-electronics-repairs": "Retail > Electronics > Repairs",
    "retail-homedecor": "Retail > Home & Decor",
    "retail-homedecor-furniture": "Retail > Home & Decor > Furniture",
    "retail-homedecor-art": "Retail > Home & Decor > Art & Prints",
    "retail-homedecor-plants": "Retail > Home & Decor > Plants & Pots",
    "retail-homedecor-lighting": "Retail > Home & Decor > Lighting",
    "retail-gifts": "Retail > Gifts & Souvenirs",
    "retail-gifts-personalised": "Retail > Gifts & Souvenirs > Personalised Gifts",
    "retail-gifts-corporate": "Retail > Gifts & Souvenirs > Corporate Gifts",
    "retail-books": "Retail > Books & Stationery",
    "retail-books-secondhand": "Retail > Books & Stationery > Second-Hand Books",
    "retail-books-art": "Retail > Books & Stationery > Art Supplies",
    "retail-grocery": "Retail > Specialty Grocery",
    "retail-grocery-organic": "Retail > Specialty Grocery > Organic & Natural",
    "retail-grocery-imported": "Retail > Specialty Grocery > Imported Foods",
    "retail-pets": "Retail > Pet Store",
    "retail-pets-supplies": "Retail > Pet Store > Pet Supplies",
    "retail-pets-grooming": "Retail > Pet Store > Pet Grooming",
    "retail-toys": "Retail > Toys & Games",
    "retail-sports-gear": "Retail > Sports Gear",
    # Entertainment
    "entertainment": "Entertainment",
    "entertainment-events": "Entertainment > Events & Venues",
    "entertainment-events-corporate": "Entertainment > Events & Venues > Corporate Events",
    "entertainment-events-birthday": "Entertainment > Events & Venues > Birthday Parties",
    "entertainment-events-wedding": "Entertainment > Events & Venues > Weddings",
    "entertainment-events-concerts": "Entertainment > Events & Venues > Concerts",
    "entertainment-gaming": "Entertainment > Gaming",
    "entertainment-gaming-arcade": "Entertainment > Gaming > Arcade",
    "entertainment-gaming-vr": "Entertainment > Gaming > VR Gaming",
    "entertainment-gaming-esports": "Entertainment > Gaming > Esports Café",
    "entertainment-gaming-boardgames": "Entertainment > Gaming > Board Game Café",
    "entertainment-arts": "Entertainment > Arts & Culture",
    "entertainment-arts-gallery": "Entertainment > Arts & Culture > Art Gallery",
    "entertainment-arts-pottery": "Entertainment > Arts & Culture > Pottery & Ceramics",
    "entertainment-arts-painting": "Entertainment > Arts & Culture > Painting Classes",
    "entertainment-arts-theatre": "Entertainment > Arts & Culture > Theatre",
    "entertainment-music": "Entertainment > Live Music",
    "entertainment-music-jazz": "Entertainment > Live Music > Jazz",
    "entertainment-music-band": "Entertainment > Live Music > Live Band",
    "entertainment-music-dj": "Entertainment > Live Music > DJ Night",
    "entertainment-escape": "Entertainment > Escape Room",
    "entertainment-comedy": "Entertainment > Comedy Club",
    "entertainment-photobooth": "Entertainment > Photo Booth / Studio",
}

TAXONOMY_IDS: frozenset[str] = frozenset(TAXONOMY.keys())


def taxonomy_prompt_block() -> str:
    return "\n".join(f"{k}: {v}" for k, v in TAXONOMY.items())


def get_label(tag_id: str) -> str:
    """Return the leaf label for a tag ID (last segment of breadcrumb)."""
    breadcrumb = TAXONOMY.get(tag_id, "")
    return breadcrumb.split(" > ")[-1] if breadcrumb else tag_id
